//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLSV
{
    using System;
    using System.Collections.Generic;
    
    public partial class LopHoc
    {
        public Nullable<System.DateTime> ngayTao { get; set; }
        public string nguoiTao { get; set; }
        public Nullable<System.DateTime> ngayCapNhat { get; set; }
        public string nguoiCapNhat { get; set; }
        public int maLopHoc { get; set; }
        public Nullable<int> maMonHoc { get; set; }
        public Nullable<int> maGiangVien { get; set; }
        public Nullable<byte> daKetThuc { get; set; }
    
        public virtual GiangVien GiangVien { get; set; }
        public virtual MonHoc MonHoc { get; set; }
    }
}
