#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLSV
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="QLSV")]
	public partial class QLSVDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertDiem(Diem instance);
    partial void UpdateDiem(Diem instance);
    partial void DeleteDiem(Diem instance);
    partial void InsertMonHoc(MonHoc instance);
    partial void UpdateMonHoc(MonHoc instance);
    partial void DeleteMonHoc(MonHoc instance);
    partial void InsertGiangVien(GiangVien instance);
    partial void UpdateGiangVien(GiangVien instance);
    partial void DeleteGiangVien(GiangVien instance);
    partial void InsertSinhVien(SinhVien instance);
    partial void UpdateSinhVien(SinhVien instance);
    partial void DeleteSinhVien(SinhVien instance);
    #endregion
		
		public QLSVDataContext() : 
				base(global::QLSV.Properties.Settings.Default.QLSVConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public QLSVDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QLSVDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QLSVDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QLSVDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Diem> Diems
		{
			get
			{
				return this.GetTable<Diem>();
			}
		}
		
		public System.Data.Linq.Table<MonHoc> MonHocs
		{
			get
			{
				return this.GetTable<MonHoc>();
			}
		}
		
		public System.Data.Linq.Table<GiangVien> GiangViens
		{
			get
			{
				return this.GetTable<GiangVien>();
			}
		}
		
		public System.Data.Linq.Table<SinhVien> SinhViens
		{
			get
			{
				return this.GetTable<SinhVien>();
			}
		}
		
		public System.Data.Linq.Table<TaiKhoan> TaiKhoans
		{
			get
			{
				return this.GetTable<TaiKhoan>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Diem")]
	public partial class Diem : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _maMonHoc;
		
		private int _maGiangVien;
		
		private int _maSinhVien;
		
		private double _diemGV1;
		
		private double _diemGV2;
		
		private System.Nullable<System.DateTime> _ngayTao;
		
		private System.Nullable<System.DateTime> _ngayCapNhat;
		
		private string _nguoiTao;
		
		private string _nguoiCapNhat;
		
		private EntityRef<MonHoc> _MonHoc;
		
		private EntityRef<GiangVien> _GiangVien;
		
		private EntityRef<SinhVien> _SinhVien;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmaMonHocChanging(int value);
    partial void OnmaMonHocChanged();
    partial void OnmaGiangVienChanging(int value);
    partial void OnmaGiangVienChanged();
    partial void OnmaSinhVienChanging(int value);
    partial void OnmaSinhVienChanged();
    partial void OndiemGV1Changing(double value);
    partial void OndiemGV1Changed();
    partial void OndiemGV2Changing(double value);
    partial void OndiemGV2Changed();
    partial void OnngayTaoChanging(System.Nullable<System.DateTime> value);
    partial void OnngayTaoChanged();
    partial void OnngayCapNhatChanging(System.Nullable<System.DateTime> value);
    partial void OnngayCapNhatChanged();
    partial void OnnguoiTaoChanging(string value);
    partial void OnnguoiTaoChanged();
    partial void OnnguoiCapNhatChanging(string value);
    partial void OnnguoiCapNhatChanged();
    #endregion
		
		public Diem()
		{
			this._MonHoc = default(EntityRef<MonHoc>);
			this._GiangVien = default(EntityRef<GiangVien>);
			this._SinhVien = default(EntityRef<SinhVien>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maMonHoc", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int maMonHoc
		{
			get
			{
				return this._maMonHoc;
			}
			set
			{
				if ((this._maMonHoc != value))
				{
					if (this._MonHoc.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmaMonHocChanging(value);
					this.SendPropertyChanging();
					this._maMonHoc = value;
					this.SendPropertyChanged("maMonHoc");
					this.OnmaMonHocChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maGiangVien", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int maGiangVien
		{
			get
			{
				return this._maGiangVien;
			}
			set
			{
				if ((this._maGiangVien != value))
				{
					if (this._GiangVien.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmaGiangVienChanging(value);
					this.SendPropertyChanging();
					this._maGiangVien = value;
					this.SendPropertyChanged("maGiangVien");
					this.OnmaGiangVienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maSinhVien", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int maSinhVien
		{
			get
			{
				return this._maSinhVien;
			}
			set
			{
				if ((this._maSinhVien != value))
				{
					if (this._SinhVien.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmaSinhVienChanging(value);
					this.SendPropertyChanging();
					this._maSinhVien = value;
					this.SendPropertyChanged("maSinhVien");
					this.OnmaSinhVienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_diemGV1", DbType="Float NOT NULL")]
		public double diemGV1
		{
			get
			{
				return this._diemGV1;
			}
			set
			{
				if ((this._diemGV1 != value))
				{
					this.OndiemGV1Changing(value);
					this.SendPropertyChanging();
					this._diemGV1 = value;
					this.SendPropertyChanged("diemGV1");
					this.OndiemGV1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_diemGV2", DbType="Float NOT NULL")]
		public double diemGV2
		{
			get
			{
				return this._diemGV2;
			}
			set
			{
				if ((this._diemGV2 != value))
				{
					this.OndiemGV2Changing(value);
					this.SendPropertyChanging();
					this._diemGV2 = value;
					this.SendPropertyChanged("diemGV2");
					this.OndiemGV2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngayTao", DbType="DateTime")]
		public System.Nullable<System.DateTime> ngayTao
		{
			get
			{
				return this._ngayTao;
			}
			set
			{
				if ((this._ngayTao != value))
				{
					this.OnngayTaoChanging(value);
					this.SendPropertyChanging();
					this._ngayTao = value;
					this.SendPropertyChanged("ngayTao");
					this.OnngayTaoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngayCapNhat", DbType="DateTime")]
		public System.Nullable<System.DateTime> ngayCapNhat
		{
			get
			{
				return this._ngayCapNhat;
			}
			set
			{
				if ((this._ngayCapNhat != value))
				{
					this.OnngayCapNhatChanging(value);
					this.SendPropertyChanging();
					this._ngayCapNhat = value;
					this.SendPropertyChanged("ngayCapNhat");
					this.OnngayCapNhatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nguoiTao", DbType="NVarChar(50)")]
		public string nguoiTao
		{
			get
			{
				return this._nguoiTao;
			}
			set
			{
				if ((this._nguoiTao != value))
				{
					this.OnnguoiTaoChanging(value);
					this.SendPropertyChanging();
					this._nguoiTao = value;
					this.SendPropertyChanged("nguoiTao");
					this.OnnguoiTaoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nguoiCapNhat", DbType="NVarChar(50)")]
		public string nguoiCapNhat
		{
			get
			{
				return this._nguoiCapNhat;
			}
			set
			{
				if ((this._nguoiCapNhat != value))
				{
					this.OnnguoiCapNhatChanging(value);
					this.SendPropertyChanging();
					this._nguoiCapNhat = value;
					this.SendPropertyChanged("nguoiCapNhat");
					this.OnnguoiCapNhatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="MonHoc_Diem", Storage="_MonHoc", ThisKey="maMonHoc", OtherKey="maMonHoc", IsForeignKey=true)]
		public MonHoc MonHoc
		{
			get
			{
				return this._MonHoc.Entity;
			}
			set
			{
				MonHoc previousValue = this._MonHoc.Entity;
				if (((previousValue != value) 
							|| (this._MonHoc.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._MonHoc.Entity = null;
						previousValue.Diems.Remove(this);
					}
					this._MonHoc.Entity = value;
					if ((value != null))
					{
						value.Diems.Add(this);
						this._maMonHoc = value.maMonHoc;
					}
					else
					{
						this._maMonHoc = default(int);
					}
					this.SendPropertyChanged("MonHoc");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="GiangVien_Diem", Storage="_GiangVien", ThisKey="maGiangVien", OtherKey="maGiangVien", IsForeignKey=true)]
		public GiangVien GiangVien
		{
			get
			{
				return this._GiangVien.Entity;
			}
			set
			{
				GiangVien previousValue = this._GiangVien.Entity;
				if (((previousValue != value) 
							|| (this._GiangVien.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._GiangVien.Entity = null;
						previousValue.Diems.Remove(this);
					}
					this._GiangVien.Entity = value;
					if ((value != null))
					{
						value.Diems.Add(this);
						this._maGiangVien = value.maGiangVien;
					}
					else
					{
						this._maGiangVien = default(int);
					}
					this.SendPropertyChanged("GiangVien");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="SinhVien_Diem", Storage="_SinhVien", ThisKey="maSinhVien", OtherKey="maSinhVien", IsForeignKey=true)]
		public SinhVien SinhVien
		{
			get
			{
				return this._SinhVien.Entity;
			}
			set
			{
				SinhVien previousValue = this._SinhVien.Entity;
				if (((previousValue != value) 
							|| (this._SinhVien.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._SinhVien.Entity = null;
						previousValue.Diems.Remove(this);
					}
					this._SinhVien.Entity = value;
					if ((value != null))
					{
						value.Diems.Add(this);
						this._maSinhVien = value.maSinhVien;
					}
					else
					{
						this._maSinhVien = default(int);
					}
					this.SendPropertyChanged("SinhVien");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.MonHoc")]
	public partial class MonHoc : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _maMonHoc;
		
		private string _tenMonHoc;
		
		private System.Nullable<int> _soTinChi;
		
		private System.Nullable<System.DateTime> _ngayTao;
		
		private System.Nullable<System.DateTime> _ngayCapNhat;
		
		private string _nguoiTao;
		
		private string _nguoiCapNhat;
		
		private EntitySet<Diem> _Diems;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmaMonHocChanging(int value);
    partial void OnmaMonHocChanged();
    partial void OntenMonHocChanging(string value);
    partial void OntenMonHocChanged();
    partial void OnsoTinChiChanging(System.Nullable<int> value);
    partial void OnsoTinChiChanged();
    partial void OnngayTaoChanging(System.Nullable<System.DateTime> value);
    partial void OnngayTaoChanged();
    partial void OnngayCapNhatChanging(System.Nullable<System.DateTime> value);
    partial void OnngayCapNhatChanged();
    partial void OnnguoiTaoChanging(string value);
    partial void OnnguoiTaoChanged();
    partial void OnnguoiCapNhatChanging(string value);
    partial void OnnguoiCapNhatChanged();
    #endregion
		
		public MonHoc()
		{
			this._Diems = new EntitySet<Diem>(new Action<Diem>(this.attach_Diems), new Action<Diem>(this.detach_Diems));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maMonHoc", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int maMonHoc
		{
			get
			{
				return this._maMonHoc;
			}
			set
			{
				if ((this._maMonHoc != value))
				{
					this.OnmaMonHocChanging(value);
					this.SendPropertyChanging();
					this._maMonHoc = value;
					this.SendPropertyChanged("maMonHoc");
					this.OnmaMonHocChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tenMonHoc", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string tenMonHoc
		{
			get
			{
				return this._tenMonHoc;
			}
			set
			{
				if ((this._tenMonHoc != value))
				{
					this.OntenMonHocChanging(value);
					this.SendPropertyChanging();
					this._tenMonHoc = value;
					this.SendPropertyChanged("tenMonHoc");
					this.OntenMonHocChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_soTinChi", DbType="Int")]
		public System.Nullable<int> soTinChi
		{
			get
			{
				return this._soTinChi;
			}
			set
			{
				if ((this._soTinChi != value))
				{
					this.OnsoTinChiChanging(value);
					this.SendPropertyChanging();
					this._soTinChi = value;
					this.SendPropertyChanged("soTinChi");
					this.OnsoTinChiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngayTao", DbType="DateTime")]
		public System.Nullable<System.DateTime> ngayTao
		{
			get
			{
				return this._ngayTao;
			}
			set
			{
				if ((this._ngayTao != value))
				{
					this.OnngayTaoChanging(value);
					this.SendPropertyChanging();
					this._ngayTao = value;
					this.SendPropertyChanged("ngayTao");
					this.OnngayTaoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngayCapNhat", DbType="DateTime")]
		public System.Nullable<System.DateTime> ngayCapNhat
		{
			get
			{
				return this._ngayCapNhat;
			}
			set
			{
				if ((this._ngayCapNhat != value))
				{
					this.OnngayCapNhatChanging(value);
					this.SendPropertyChanging();
					this._ngayCapNhat = value;
					this.SendPropertyChanged("ngayCapNhat");
					this.OnngayCapNhatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nguoiTao", DbType="NVarChar(50)")]
		public string nguoiTao
		{
			get
			{
				return this._nguoiTao;
			}
			set
			{
				if ((this._nguoiTao != value))
				{
					this.OnnguoiTaoChanging(value);
					this.SendPropertyChanging();
					this._nguoiTao = value;
					this.SendPropertyChanged("nguoiTao");
					this.OnnguoiTaoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nguoiCapNhat", DbType="NVarChar(50)")]
		public string nguoiCapNhat
		{
			get
			{
				return this._nguoiCapNhat;
			}
			set
			{
				if ((this._nguoiCapNhat != value))
				{
					this.OnnguoiCapNhatChanging(value);
					this.SendPropertyChanging();
					this._nguoiCapNhat = value;
					this.SendPropertyChanged("nguoiCapNhat");
					this.OnnguoiCapNhatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="MonHoc_Diem", Storage="_Diems", ThisKey="maMonHoc", OtherKey="maMonHoc")]
		public EntitySet<Diem> Diems
		{
			get
			{
				return this._Diems;
			}
			set
			{
				this._Diems.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Diems(Diem entity)
		{
			this.SendPropertyChanging();
			entity.MonHoc = this;
		}
		
		private void detach_Diems(Diem entity)
		{
			this.SendPropertyChanging();
			entity.MonHoc = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.GiangVien")]
	public partial class GiangVien : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _maGiangVien;
		
		private string _ho;
		
		private string _ten;
		
		private System.Nullable<byte> _gioiTinh;
		
		private System.Nullable<System.DateTime> _namSinh;
		
		private string _diaChi;
		
		private int _soDienThoai;
		
		private string _email;
		
		private System.Nullable<System.DateTime> _ngayTao;
		
		private System.Nullable<System.DateTime> _ngayCapNhat;
		
		private string _nguoiTao;
		
		private string _nguoiCapNhat;
		
		private EntitySet<Diem> _Diems;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmaGiangVienChanging(int value);
    partial void OnmaGiangVienChanged();
    partial void OnhoChanging(string value);
    partial void OnhoChanged();
    partial void OntenChanging(string value);
    partial void OntenChanged();
    partial void OngioiTinhChanging(System.Nullable<byte> value);
    partial void OngioiTinhChanged();
    partial void OnnamSinhChanging(System.Nullable<System.DateTime> value);
    partial void OnnamSinhChanged();
    partial void OndiaChiChanging(string value);
    partial void OndiaChiChanged();
    partial void OnsoDienThoaiChanging(int value);
    partial void OnsoDienThoaiChanged();
    partial void OnemailChanging(string value);
    partial void OnemailChanged();
    partial void OnngayTaoChanging(System.Nullable<System.DateTime> value);
    partial void OnngayTaoChanged();
    partial void OnngayCapNhatChanging(System.Nullable<System.DateTime> value);
    partial void OnngayCapNhatChanged();
    partial void OnnguoiTaoChanging(string value);
    partial void OnnguoiTaoChanged();
    partial void OnnguoiCapNhatChanging(string value);
    partial void OnnguoiCapNhatChanged();
    #endregion
		
		public GiangVien()
		{
			this._Diems = new EntitySet<Diem>(new Action<Diem>(this.attach_Diems), new Action<Diem>(this.detach_Diems));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maGiangVien", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int maGiangVien
		{
			get
			{
				return this._maGiangVien;
			}
			set
			{
				if ((this._maGiangVien != value))
				{
					this.OnmaGiangVienChanging(value);
					this.SendPropertyChanging();
					this._maGiangVien = value;
					this.SendPropertyChanged("maGiangVien");
					this.OnmaGiangVienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ho", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string ho
		{
			get
			{
				return this._ho;
			}
			set
			{
				if ((this._ho != value))
				{
					this.OnhoChanging(value);
					this.SendPropertyChanging();
					this._ho = value;
					this.SendPropertyChanged("ho");
					this.OnhoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ten", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string ten
		{
			get
			{
				return this._ten;
			}
			set
			{
				if ((this._ten != value))
				{
					this.OntenChanging(value);
					this.SendPropertyChanging();
					this._ten = value;
					this.SendPropertyChanged("ten");
					this.OntenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gioiTinh", DbType="TinyInt")]
		public System.Nullable<byte> gioiTinh
		{
			get
			{
				return this._gioiTinh;
			}
			set
			{
				if ((this._gioiTinh != value))
				{
					this.OngioiTinhChanging(value);
					this.SendPropertyChanging();
					this._gioiTinh = value;
					this.SendPropertyChanged("gioiTinh");
					this.OngioiTinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_namSinh", DbType="Date")]
		public System.Nullable<System.DateTime> namSinh
		{
			get
			{
				return this._namSinh;
			}
			set
			{
				if ((this._namSinh != value))
				{
					this.OnnamSinhChanging(value);
					this.SendPropertyChanging();
					this._namSinh = value;
					this.SendPropertyChanged("namSinh");
					this.OnnamSinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_diaChi", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string diaChi
		{
			get
			{
				return this._diaChi;
			}
			set
			{
				if ((this._diaChi != value))
				{
					this.OndiaChiChanging(value);
					this.SendPropertyChanging();
					this._diaChi = value;
					this.SendPropertyChanged("diaChi");
					this.OndiaChiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_soDienThoai", DbType="Int NOT NULL")]
		public int soDienThoai
		{
			get
			{
				return this._soDienThoai;
			}
			set
			{
				if ((this._soDienThoai != value))
				{
					this.OnsoDienThoaiChanging(value);
					this.SendPropertyChanging();
					this._soDienThoai = value;
					this.SendPropertyChanged("soDienThoai");
					this.OnsoDienThoaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string email
		{
			get
			{
				return this._email;
			}
			set
			{
				if ((this._email != value))
				{
					this.OnemailChanging(value);
					this.SendPropertyChanging();
					this._email = value;
					this.SendPropertyChanged("email");
					this.OnemailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngayTao", DbType="DateTime")]
		public System.Nullable<System.DateTime> ngayTao
		{
			get
			{
				return this._ngayTao;
			}
			set
			{
				if ((this._ngayTao != value))
				{
					this.OnngayTaoChanging(value);
					this.SendPropertyChanging();
					this._ngayTao = value;
					this.SendPropertyChanged("ngayTao");
					this.OnngayTaoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngayCapNhat", DbType="DateTime")]
		public System.Nullable<System.DateTime> ngayCapNhat
		{
			get
			{
				return this._ngayCapNhat;
			}
			set
			{
				if ((this._ngayCapNhat != value))
				{
					this.OnngayCapNhatChanging(value);
					this.SendPropertyChanging();
					this._ngayCapNhat = value;
					this.SendPropertyChanged("ngayCapNhat");
					this.OnngayCapNhatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nguoiTao", DbType="NVarChar(50)")]
		public string nguoiTao
		{
			get
			{
				return this._nguoiTao;
			}
			set
			{
				if ((this._nguoiTao != value))
				{
					this.OnnguoiTaoChanging(value);
					this.SendPropertyChanging();
					this._nguoiTao = value;
					this.SendPropertyChanged("nguoiTao");
					this.OnnguoiTaoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nguoiCapNhat", DbType="NVarChar(50)")]
		public string nguoiCapNhat
		{
			get
			{
				return this._nguoiCapNhat;
			}
			set
			{
				if ((this._nguoiCapNhat != value))
				{
					this.OnnguoiCapNhatChanging(value);
					this.SendPropertyChanging();
					this._nguoiCapNhat = value;
					this.SendPropertyChanged("nguoiCapNhat");
					this.OnnguoiCapNhatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="GiangVien_Diem", Storage="_Diems", ThisKey="maGiangVien", OtherKey="maGiangVien")]
		public EntitySet<Diem> Diems
		{
			get
			{
				return this._Diems;
			}
			set
			{
				this._Diems.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Diems(Diem entity)
		{
			this.SendPropertyChanging();
			entity.GiangVien = this;
		}
		
		private void detach_Diems(Diem entity)
		{
			this.SendPropertyChanging();
			entity.GiangVien = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.SinhVien")]
	public partial class SinhVien : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _maSinhVien;
		
		private string _Ho;
		
		private string _Ten;
		
		private byte _gioiTinh;
		
		private System.Nullable<System.DateTime> _namSinh;
		
		private string _queQuan;
		
		private int _dienThoai;
		
		private string _diaChi;
		
		private System.Nullable<System.DateTime> _ngayTao;
		
		private System.Nullable<System.DateTime> _ngayCapNhat;
		
		private string _nguoiTao;
		
		private string _nguoiCapNhat;
		
		private EntitySet<Diem> _Diems;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmaSinhVienChanging(int value);
    partial void OnmaSinhVienChanged();
    partial void OnHoChanging(string value);
    partial void OnHoChanged();
    partial void OnTenChanging(string value);
    partial void OnTenChanged();
    partial void OngioiTinhChanging(byte value);
    partial void OngioiTinhChanged();
    partial void OnnamSinhChanging(System.Nullable<System.DateTime> value);
    partial void OnnamSinhChanged();
    partial void OnqueQuanChanging(string value);
    partial void OnqueQuanChanged();
    partial void OndienThoaiChanging(int value);
    partial void OndienThoaiChanged();
    partial void OndiaChiChanging(string value);
    partial void OndiaChiChanged();
    partial void OnngayTaoChanging(System.Nullable<System.DateTime> value);
    partial void OnngayTaoChanged();
    partial void OnngayCapNhatChanging(System.Nullable<System.DateTime> value);
    partial void OnngayCapNhatChanged();
    partial void OnnguoiTaoChanging(string value);
    partial void OnnguoiTaoChanged();
    partial void OnnguoiCapNhatChanging(string value);
    partial void OnnguoiCapNhatChanged();
    #endregion
		
		public SinhVien()
		{
			this._Diems = new EntitySet<Diem>(new Action<Diem>(this.attach_Diems), new Action<Diem>(this.detach_Diems));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maSinhVien", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int maSinhVien
		{
			get
			{
				return this._maSinhVien;
			}
			set
			{
				if ((this._maSinhVien != value))
				{
					this.OnmaSinhVienChanging(value);
					this.SendPropertyChanging();
					this._maSinhVien = value;
					this.SendPropertyChanged("maSinhVien");
					this.OnmaSinhVienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ho", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Ho
		{
			get
			{
				return this._Ho;
			}
			set
			{
				if ((this._Ho != value))
				{
					this.OnHoChanging(value);
					this.SendPropertyChanging();
					this._Ho = value;
					this.SendPropertyChanged("Ho");
					this.OnHoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ten", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Ten
		{
			get
			{
				return this._Ten;
			}
			set
			{
				if ((this._Ten != value))
				{
					this.OnTenChanging(value);
					this.SendPropertyChanging();
					this._Ten = value;
					this.SendPropertyChanged("Ten");
					this.OnTenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gioiTinh", DbType="TinyInt NOT NULL")]
		public byte gioiTinh
		{
			get
			{
				return this._gioiTinh;
			}
			set
			{
				if ((this._gioiTinh != value))
				{
					this.OngioiTinhChanging(value);
					this.SendPropertyChanging();
					this._gioiTinh = value;
					this.SendPropertyChanged("gioiTinh");
					this.OngioiTinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_namSinh", DbType="Date")]
		public System.Nullable<System.DateTime> namSinh
		{
			get
			{
				return this._namSinh;
			}
			set
			{
				if ((this._namSinh != value))
				{
					this.OnnamSinhChanging(value);
					this.SendPropertyChanging();
					this._namSinh = value;
					this.SendPropertyChanged("namSinh");
					this.OnnamSinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_queQuan", DbType="NVarChar(50)")]
		public string queQuan
		{
			get
			{
				return this._queQuan;
			}
			set
			{
				if ((this._queQuan != value))
				{
					this.OnqueQuanChanging(value);
					this.SendPropertyChanging();
					this._queQuan = value;
					this.SendPropertyChanged("queQuan");
					this.OnqueQuanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dienThoai", DbType="Int NOT NULL")]
		public int dienThoai
		{
			get
			{
				return this._dienThoai;
			}
			set
			{
				if ((this._dienThoai != value))
				{
					this.OndienThoaiChanging(value);
					this.SendPropertyChanging();
					this._dienThoai = value;
					this.SendPropertyChanged("dienThoai");
					this.OndienThoaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_diaChi", DbType="NVarChar(50)")]
		public string diaChi
		{
			get
			{
				return this._diaChi;
			}
			set
			{
				if ((this._diaChi != value))
				{
					this.OndiaChiChanging(value);
					this.SendPropertyChanging();
					this._diaChi = value;
					this.SendPropertyChanged("diaChi");
					this.OndiaChiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngayTao", DbType="DateTime")]
		public System.Nullable<System.DateTime> ngayTao
		{
			get
			{
				return this._ngayTao;
			}
			set
			{
				if ((this._ngayTao != value))
				{
					this.OnngayTaoChanging(value);
					this.SendPropertyChanging();
					this._ngayTao = value;
					this.SendPropertyChanged("ngayTao");
					this.OnngayTaoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngayCapNhat", DbType="DateTime")]
		public System.Nullable<System.DateTime> ngayCapNhat
		{
			get
			{
				return this._ngayCapNhat;
			}
			set
			{
				if ((this._ngayCapNhat != value))
				{
					this.OnngayCapNhatChanging(value);
					this.SendPropertyChanging();
					this._ngayCapNhat = value;
					this.SendPropertyChanged("ngayCapNhat");
					this.OnngayCapNhatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nguoiTao", DbType="NVarChar(50)")]
		public string nguoiTao
		{
			get
			{
				return this._nguoiTao;
			}
			set
			{
				if ((this._nguoiTao != value))
				{
					this.OnnguoiTaoChanging(value);
					this.SendPropertyChanging();
					this._nguoiTao = value;
					this.SendPropertyChanged("nguoiTao");
					this.OnnguoiTaoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nguoiCapNhat", DbType="NVarChar(50)")]
		public string nguoiCapNhat
		{
			get
			{
				return this._nguoiCapNhat;
			}
			set
			{
				if ((this._nguoiCapNhat != value))
				{
					this.OnnguoiCapNhatChanging(value);
					this.SendPropertyChanging();
					this._nguoiCapNhat = value;
					this.SendPropertyChanged("nguoiCapNhat");
					this.OnnguoiCapNhatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="SinhVien_Diem", Storage="_Diems", ThisKey="maSinhVien", OtherKey="maSinhVien")]
		public EntitySet<Diem> Diems
		{
			get
			{
				return this._Diems;
			}
			set
			{
				this._Diems.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Diems(Diem entity)
		{
			this.SendPropertyChanging();
			entity.SinhVien = this;
		}
		
		private void detach_Diems(Diem entity)
		{
			this.SendPropertyChanging();
			entity.SinhVien = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TaiKhoan")]
	public partial class TaiKhoan
	{
		
		private string _tenTaiKhoan;
		
		private string _matKhau;
		
		public TaiKhoan()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tenTaiKhoan", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string tenTaiKhoan
		{
			get
			{
				return this._tenTaiKhoan;
			}
			set
			{
				if ((this._tenTaiKhoan != value))
				{
					this._tenTaiKhoan = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_matKhau", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string matKhau
		{
			get
			{
				return this._matKhau;
			}
			set
			{
				if ((this._matKhau != value))
				{
					this._matKhau = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
